routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\App;

Route::get('locale/{locale}', function ($locale){
    Session::put('hr_locale',$locale);
    return redirect("/");
});


Route::get('reboot',function (){
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
});


Route::get('/', function () {
    return view('auth.login');
})->name('/');


Route::get('dynamic-web','backend\WebController@index');
Route::get('assign','backend\WebController@assign');

Auth::routes();


Route::middleware(['CheckPermit','auth'])->group(function (){

    Route::prefix('UserManagement')->group(function (){
        /* Custom Registration Start */
        Route::get('add-user','backend\UserController@index')->name('user.add');
        Route::get('view-user','backend\UserController@index')->name('user.view');
        Route::post('store-user','backend\UserController@store')->name('user.store');
        Route::get('edit-user/{id}','backend\UserController@edit')->name('user.edit');
        Route::post('update-user/{id}','backend\UserController@update')->name('user.update');
        Route::post('destroy-user','backend\UserController@destroy')->name('user.destroy');
        /* Custom Registration Start */
    });

    /* Role & Permission Start */
    Route::prefix('Role-Permission')->group(function (){

        /* Permission Settings  Start
        === We Can Enable it if you wants to add Route information dynamically through Form.
        */
        /*Route::get("add-permission","backend\PermissionController@index")->name('permission.add');
        Route::post("/save-permission","backend\PermissionController@store")->name('permission.store');
        Route::get("/edit-permission/{id}","backend\PermissionController@edit")->name('permission.edit');
        Route::post("/update-permission/{id}","backend\PermissionController@update")->name('permission.update');
        Route::post("/destroy-permission","backend\PermissionController@destroy")->name('permission.destroy');*/
        /* Permission Settings  Start */

        /* Role Create Start  */
        Route::get('add-role','backend\RoleController@index')->name('role.add');
        Route::get('view-role','backend\RoleController@index')->name('role.view');
        Route::post('store-role','backend\RoleController@store')->name('role.store');
        Route::get('edit-role/{id}','backend\RoleController@edit')->name('role.edit');
        Route::post('update-role/{id}','backend\RoleController@update')->name('role.update');
        Route::post('destroy-role','backend\RoleController@destroy')->name('role.destroy');
        /* Role Create End  */
    });
    /* Role & Permission End */

    Route::prefix('admin')->group(function (){
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('change-password','backend\UserController@changePassword')->name('admin.password-change');
        Route::post('update-admin/{id}','backend\UserController@updateAdmin')->name('admin.update');
    });

    Route::prefix('employee')->name('employee.')->group(function (){
        $employeeController = 'backend\EmployeeController@';
        Route::get('/new-employee',$employeeController.'index')->name('add');
        Route::get('/edit-employee/{id}',$employeeController.'edit')->name('edit');
        Route::get('/view-employee',$employeeController.'view')->name('view');
        Route::post('/store-employee',$employeeController.'store')->name('store');
        Route::post('/update-employee/{id}',$employeeController.'update')->name('update');
        Route::post('/destroy-employee',$employeeController.'destroy')->name('destroy');
        Route::get('/archive-employee',$employeeController.'archive')->name('archive');
        Route::post('/restore-employee/{id}',$employeeController.'restore')->name('restore');
    });

    Route::prefix('attendance')->name('attendance.')->group(function (){
        $attendanceController = 'backend\AttendanceController@';
        Route::get('/new-attendance',$attendanceController.'index')->name('add');
        Route::get('/edit-attendance/{id}',$attendanceController.'edit')->name('edit');
        Route::get('/view-attendance',$attendanceController.'view')->name('view');
        Route::post('/store-attendance',$attendanceController.'store')->name('store');
        Route::post('/single-update-attendance/{id}',$attendanceController.'singleUpdate')->name('single-update');
    });
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
class Employee extends Model
{
    use SoftDeletes;
    protected $table = 'employees';
    protected $fillable = ['name','join_date','salary', 'avatar', 'gender', 'religion', 'nationality', 'nid', 'dob', 'phone',
        'email', 'present_address', 'permanent_address', 'designation_id', 'isActive', 'deleted_at'];

    public function designation()
    {
        return $this->belongsTo(Designation::class);
    }
}

app/Http/Controllers/backend/EmployeeController.php
<?php

namespace App\Http\Controllers\backend;

use App\Designation;
use App\Employee;
use App\Http\Controllers\Controller;
use App\Http\Requests\EmployeeRegister;
use App\Http\Requests\EmployeeUpdate;
use Illuminate\Http\Request;
use App\Traits\StoreImageTrait;

class EmployeeController extends Controller
{
    use StoreImageTrait;

    public $path = null;
    public function index()
    {
        $data['designations'] = Designation::query()->pluck('name','id');
        return view('employee.add-employee')->with($data);
    }

    public function view()
    {
        $data['employees'] = Employee::query()->where('isActive','!=',0)->get();
        return view('employee.view-employee')->with($data);

    }

    public function store(EmployeeRegister $request)
    {
        $data = $request->except('avatar');
        if ($request->hasFile('avatar'))
        {
            $this->path = public_path('upload/employee');
            $data['avatar'] = $this->ImageStore($request->file('avatar'),$this->path);
        }
        Employee::query()->create($data);
        session()->flash('success','Employee Registration Complete');
        return redirect()->route('employee.add');
    }

    public function edit($id)
    {
        $id = decrypt($id);
        $data['employee'] = Employee::query()->findOrFail($id);
        $data['designations'] = Designation::query()->pluck('name','id');
        return view('employee.edit-employee')->with($data);
    }

    public function update(EmployeeUpdate $request,$id)
    {
        $id = decrypt($id);
        $employee = Employee::query()->findOrFail($id);

        $data = $request->except('avatar');

        if ($request->hasFile('avatar'))
        {
            /* if exits unlink old one */
            $this->path = public_path('upload/employee');
            if ($employee->avatar !=null && file_exists($this->path.'/'.$employee->avatar)){
                $this->unlinkImage($this->path.'/'.$employee->avatar);
            }

            $data['avatar'] = $this->ImageStore($request->file('avatar'),$this->path);
        }

        $employee->update($data);
        session()->flash('success','Employee Updated');
        return redirect()->route('employee.view');
    }

    public function destroy(Request $request)
    {
        $id = decrypt($request->id);
        $delete = Employee::query()->findOrFail($id);
        $delete->delete();
    }

    public function archive()
    {
        $employees = Employee::query()->onlyTrashed()->get();
        return view('employee.archive-employee',compact('employees'));
    }

    public function restore(Request $request,$id)
    {
        $id = decrypt($id);
        $employee = Employee::query()->withTrashed()->findOrFail($id);
        $employee->update(['deleted_at'=>null]);
        session()->flash('success','Employee Recover successfully.');
        return redirect()->route('employee.view');
    }

}

resources/views/employee/add-employee.blade.php
@extends('layouts.admin')

@section('title','New Employee | HR Application')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Employee Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Employee </li>
                    </ol>
                </div><!-- /.col -->

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('employee.view') }}" class="btn btn-success pull-right"> ALL Employees</a>
                            <a href="{{ route('employee.archive') }}" class="btn btn-danger pull-right" style="float:
                            right"> Archive Employees</a>
                        </div>
                    </div>

                </div>

            </div><!-- /.row -->


        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">New Employee</h3>
                        </div>
                        <div class="card-body">
                            {{ Form::model($employee = new \App\Employee(),['route'=>'employee.store','method'=>'post', 'files'=>true]) }}
                            <div class="row">
                                @include('employee.form-employee')
                            </div>
                            {{ Form::submit('Register Employee',['class'=>'btn btn-success']) }}
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("#dataTable").DataTable();
        });
    </script>
@endsection

resources/views/employee/archive-employee.blade.php
@extends('layouts.admin')
@section('title','ALL Employee - HR Application')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Employee Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">View Employee </li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">
                <!-- ./col -->
                <div class="col-lg-12 col-xs-12">
                    {{-- all users retrive start --}}
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">ALL Employee</h3>
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table table-hover" id="dataTable">
                                <thead>
                                <tr>
                                    <th>#SL</th>
                                    <th>Name</th>
                                    <th>Avatar</th>
                                    <th>Designation</th>
                                    <th>Join Date</th>
                                    <th>Salary</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($employees->count()>0)
                                    @foreach($employees as $key=>$employee)
                                        <tr>
                                            <td>{{ $loop->iteration }}</td>
                                            <td>{{ $employee->name }}</td>
                                            <td>
                                                <img src="{{ $employee->avatar !=null ? asset('upload/employee/'
                                                    .$employee->avatar) : asset('upload/noimage.png') }}"
                                                     style="height:
                                                    100px;width: 100px" alt="">
                                            </td>
                                            <td>{{ $employee->designation->name }}</td>
                                            <td>{{ $employee->join_date }}</td>
                                            <td>{{ $employee->salary }}</td>
                                            <td>{{ $employee->isActive }}</td>
                                            <td>
                                                {{ Form::open(['route'=>['employee.restore', encrypt($employee->id)]]) }}
                                                <button type="submit" class="btn btn-info"> <i class="fa
                                                fa-recycle"></i> </button>
                                                {{ Form::close() }}
                                            </td>
</tr>
@endforeach
@endif
</tbody>
</table>
</div>
{{-- all users retrive end --}}
</div>

</div>

</div>


</section>
<!-- /.content -->

@endsection

@section('script')
<script>
$(document).ready(function () {
$("#dataTable").DataTable();
});
</script>
@endsection

resources/views/employee/edit-employee.blade.php
@extends('layouts.admin')

@section('title','New Employee | HR Application')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Employee Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Employee </li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">New Employee</h3>
                        </div>
                        <div class="card-body">
                            {{ Form::model($employee,['route'=>['employee.update', encrypt($employee->id)],'method'=>'post',
                            'files'=>true]) }}
                            <div class="row">
                                @include('employee.form-employee')
                            </div>
                            {{ Form::submit('Update Employee',['class'=>'btn btn-success']) }}
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("#dataTable").DataTable();
        });
    </script>
@endsection

resources/views/employee/form-employee.blade.php
<div class="col-lg-3">
    <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }} ">
        {{ Form::label('','Name *') }}
          @if($employee)
            {{ Form::hidden('id',encrypt($employee->id)) }}
          @endif
        {{ Form::text('name',null,['class'=>'form-control','placeholder'=>'Ex.John Doe']) }}

        @if($errors->has('name'))
            <span class="strong">
                <strong class="help-block"> {{ $errors->first('name') }}</strong>
            </span>
        @endif
    </div>
</div>


<div class="col-lg-3">
    <div class="form-group @error('nid') has-error @enderror ">
        {{ Form::label('','NID *') }}
        {{ Form::text('nid',null,['class'=>'form-control','placeholder'=>'Ex.John Doe']) }}

        @error('nid')
            <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-3">
    <div class="form-group @error('avatar') has-error @enderror ">
        {{ Form::label('','Avatar') }}
        {{ Form::file('avatar',['class'=>'form-control','accept'=>'image/*']) }}

        @error('avatar')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>



<div class="col-lg-3">
    <div class="form-group @error('dob') has-error @enderror ">
        {{ Form::label('','Date of Birth *') }}
        {{ Form::date('dob',null,['class'=>'form-control','placeholder'=>'Ex. 1990-04-25']) }}

        @error('dob')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-3">
    <div class="form-group @error('phone') has-error @enderror ">
        {{ Form::label('','Phone *') }}
        {{ Form::text('phone',null,['class'=>'form-control','placeholder'=>'Ex. +8801**********']) }}

        @error('phone')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="col-lg-3">
    <div class="form-group @error('email') has-error @enderror ">
        {{ Form::label('','Email') }}
        {{ Form::text('email',null,['class'=>'form-control','placeholder'=>'Ex. example@example.com']) }}

        @error('email')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-3">
    <div class="form-group @error('designation_id') has-error @enderror ">
        {{ Form::label('','Designation *') }}
        {{ Form::select('designation_id',$designations,$employee ? $employee->designation_id : false,['class'=>'form-control']) }}

        @error('designation_id')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-3">
    <div class="form-group @error('religion') has-error @enderror ">
        {{ Form::label('','Religion *') }}
        {{ Form::select('religion',['islam'=>'Islam','hindu'=>'Hindu','buddha'=>'Buddha','krishtian'=>'Krishtian'],
        $employee ? $employee->religion : false,
        ['class'=>'form-control']) }}

        @error('religion')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-3">
    <div class="form-group @error('gender') has-error @enderror ">
        {{ Form::label('','Gender *') }}
        {{ Form::select('gender',['male'=>'Male','female'=>'Female','other'=>'Third Gender'],$employee ? $employee->gender : false,
        ['class'=>'form-control']) }}

        @error('gender')
            <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="col-lg-3">
    <div class="form-group @error('nationality') has-error @enderror ">
        {{ Form::label('','Nationality *') }}
        {{ Form::text('nationality',null,['class'=>'form-control','placeholder'=>'Ex.Bangladeshi']) }}

        @error('nationality')
             <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="col-lg-3">
    <div class="form-group @error('join_date') has-error @enderror ">
        {{ Form::label('','Joining Date *') }}
        {{ Form::date('join_date',null,['class'=>'form-control','placeholder'=>'Ex.2020-06-21']) }}

        @error('join_date')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="col-lg-3">
    <div class="form-group @error('salary') has-error @enderror ">
        {{ Form::label('','Starting Salary *') }}
        {{ Form::number('salary',null,['class'=>'form-control','placeholder'=>'Ex.40,000']) }}

        @error('salary')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-6">
    <div class="form-group @error('present_address') has-error @enderror ">
        {{ Form::label('','Present Address *') }}
        {{ Form::textarea('present_address',null,['class'=>'form-control','cols'=>10,'rows'=>10]) }}

        @error('present_address')
            <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>



<div class="col-lg-6">
    <div class="form-group @error('permanent_address') has-error @enderror ">
        {{ Form::label('','Permanent Address *') }}
        {{ Form::textarea('permanent_address',null,['class'=>'form-control','cols'=>10,'rows'=>10]) }}

        @error('permanent_address')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

resources/views/employee/view-employee.blade.php
@extends('layouts.admin')
@section('title','ALL Employee - HR Application')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Employee Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">View Employee </li>
                    </ol>
                </div><!-- /.col -->

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('employee.add') }}" class="btn btn-success pull-right"> New Employee</a>
                            <a href="{{ route('employee.archive') }}" class="btn btn-danger pull-right" style="float:
                            right"> Archive Employees</a>
                        </div>
                    </div>
                </div>


            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">
                <!-- ./col -->
                <div class="col-lg-12 col-xs-12">
                    {{-- all users retrive start --}}
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">ALL Employee</h3>
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table table-hover" id="dataTable">
                                <thead>
                                <tr>
                                    <th>#SL</th>
                                    <th>Name</th>
                                    <th>Avatar</th>
                                    <th>Designation</th>
                                    <th>Join Date</th>
                                    <th>Salary</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @if($employees->count()>0)
                                        @foreach($employees as $key=>$employee)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $employee->name }}</td>
                                                <td>
                                                    <img src="{{ $employee->avatar !=null ? asset('upload/employee/'
                                                    .$employee->avatar) : asset('upload/noimage.png') }}"
                                                         style="height:
                                                    100px;width: 100px" alt="">
                                                </td>
                                                <td>{{ $employee->designation->name }}</td>
                                                <td>{{ $employee->join_date }}</td>
                                                <td>{{ $employee->salary }}</td>
                                                <td>{{ $employee->isActive }}</td>
                                                <td>
                                                    <a href="#" class="fa fa-user-cog bg-info p-2 rounded"></a>
                                                    <a href="{{ route('employee.edit',encrypt( $employee->id)) }}" class="fa
                                                    fa-edit bg-success ml-2 p-2
                                                    rounded"></a>
                                                    <button type="button"
                                                            data-url="{{ route('employee.destroy') }}"
                                                            data-id="{{ encrypt($employee->id) }}"
                                                            class="fa fa-trash erase bg-danger ml-2  p-2   rounded">

                                                    </button>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                </tbody>
                            </table>
                        </div>
                        {{-- all users retrive end --}}
                    </div>

                </div>

            </div>


    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("#dataTable").DataTable();
        });
    </script>
@endsection