routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\App;

Route::get('locale/{locale}', function ($locale){
    Session::put('hr_locale',$locale);
    return redirect("/");
});


Route::get('reboot',function (){
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
});


Route::get('/', function () {
    return view('auth.login');
})->name('/');


Route::get('dynamic-web','backend\WebController@index');
Route::get('assign','backend\WebController@assign');

Auth::routes();


Route::middleware(['CheckPermit','auth'])->group(function (){

    Route::prefix('UserManagement')->group(function (){
        /* Custom Registration Start */
        Route::get('add-user','backend\UserController@index')->name('user.add');
        Route::get('view-user','backend\UserController@index')->name('user.view');
        Route::post('store-user','backend\UserController@store')->name('user.store');
        Route::get('edit-user/{id}','backend\UserController@edit')->name('user.edit');
        Route::post('update-user/{id}','backend\UserController@update')->name('user.update');
        Route::post('destroy-user','backend\UserController@destroy')->name('user.destroy');
        /* Custom Registration Start */
    });

    /* Role & Permission Start */
    Route::prefix('Role-Permission')->group(function (){

        /* Permission Settings  Start
        === We Can Enable it if you wants to add Route information dynamically through Form.
        */
        /*Route::get("add-permission","backend\PermissionController@index")->name('permission.add');
        Route::post("/save-permission","backend\PermissionController@store")->name('permission.store');
        Route::get("/edit-permission/{id}","backend\PermissionController@edit")->name('permission.edit');
        Route::post("/update-permission/{id}","backend\PermissionController@update")->name('permission.update');
        Route::post("/destroy-permission","backend\PermissionController@destroy")->name('permission.destroy');*/
        /* Permission Settings  Start */

        /* Role Create Start  */
        Route::get('add-role','backend\RoleController@index')->name('role.add');
        Route::get('view-role','backend\RoleController@index')->name('role.view');
        Route::post('store-role','backend\RoleController@store')->name('role.store');
        Route::get('edit-role/{id}','backend\RoleController@edit')->name('role.edit');
        Route::post('update-role/{id}','backend\RoleController@update')->name('role.update');
        Route::post('destroy-role','backend\RoleController@destroy')->name('role.destroy');
        /* Role Create End  */
    });
    /* Role & Permission End */

    Route::prefix('admin')->group(function (){
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('change-password','backend\UserController@changePassword')->name('admin.password-change');
        Route::post('update-admin/{id}','backend\UserController@updateAdmin')->name('admin.update');
    });

    Route::prefix('employee')->name('employee.')->group(function (){
        $employeeController = 'backend\EmployeeController@';
        Route::get('/new-employee',$employeeController.'index')->name('add');
        Route::get('/edit-employee/{id}',$employeeController.'edit')->name('edit');
        Route::get('/view-employee',$employeeController.'view')->name('view');
        Route::post('/store-employee',$employeeController.'store')->name('store');
        Route::post('/update-employee/{id}',$employeeController.'update')->name('update');
        Route::post('/destroy-employee',$employeeController.'destroy')->name('destroy');
        Route::get('/archive-employee',$employeeController.'archive')->name('archive');
        Route::post('/restore-employee/{id}',$employeeController.'restore')->name('restore');
    });

    Route::prefix('attendance')->name('attendance.')->group(function (){
        $attendanceController = 'backend\AttendanceController@';
        Route::get('/new-attendance',$attendanceController.'index')->name('add');
        Route::get('/edit-attendance/{id}',$attendanceController.'edit')->name('edit');
        Route::get('/view-attendance',$attendanceController.'view')->name('view');
        Route::post('/store-attendance',$attendanceController.'store')->name('store');
        Route::post('/single-update-attendance/{id}',$attendanceController.'singleUpdate')->name('single-update');
    });
});

resources/views/include/admin-menu.blade.php
<li class="nav-item has-treeview">
    <a href="#" class="nav-link active">
        <i class="nav-icon fas fa-tachometer-alt"></i>
        <p>
            Dashboard
            <i class="right fas fa-angle-left"></i>
        </p>
    </a>
</li>

{{-- Menu Header [menu-open]--}}

{{-- Menu Option [active]--}}

@php

    $prefix = Request::route()->getPrefix();
    $route  = Route::current()->getName();
   // dd($prefix,$route);
    $auth = \Illuminate\Support\Facades\Auth::user();

@endphp
    
{{-- User Management --}}

@if($auth && $auth->roles->count()>0)
    {{-- Menus --}}
    @foreach($auth->roles as $key=>$role)
        {{-- Role Menus--}}
            @foreach($role->prefixMenus($role->id) as $in=>$menu)

                <li class="nav-item has-treeview {{ $prefix ==$menu->prefix ? 'menu-open' : '' }}">

                    <a href="#" class="nav-link {{  $prefix == $menu->prefix  ? 'active' : '' }}">
                        <i class="nav-icon fas fa-user-astronaut"></i>
                        <p>
                            {{ $menu->prefix }}
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">

                    @php
                        $prefixMenu = \App\MenuRole::query()->where('prefix','=',$menu->prefix)->get()
                    @endphp

                    @if($prefixMenu->count()>0)
                        @foreach($prefixMenu as $p=>$pmenu)
                            @if($pmenu->isGet == 'GET' &&  $pmenu->isEdit == 'add')
                                <li class="nav-item ">
                                    <a href="{{ route($pmenu->route) }}" class="nav-link {{ $route == $pmenu->route ?
                                    'active' : ''
                                    }}">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>{{ $pmenu->name }}</p>
                                    </a>
                                </li>
                            @endif
                        @endforeach
                    @else

                    @endif
                    </ul>

                </li>

            @endforeach
    @endforeach
@else

@endif




{{-- Role Management --}}

{{--

<li class="nav-item has-treeview {{ $prefix =='/Role-Permission' ? 'menu-open' : '' }}">

    <a href="#" class="nav-link {{ $prefix =='/Role-Permission' ? 'active' : '' }}">
        <i class="nav-icon fas fa-cog"></i>
        <p>
            Role Management
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>

    <ul class="nav nav-treeview">

        <li class="nav-item ">
            <a href="{{ route('role.add') }}" class="nav-link {{ $route == 'role.add' ? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p>Manage Role</p>
            </a>
        </li>

      --}}
{{--  <li class="nav-item ">
            <a href="{{ route('permission.add') }}" class="nav-link {{ $route == 'permission.add' ? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p>Manage Permission</p>
            </a>
        </li>--}}{{--




    </ul>
</li>



<li class="nav-item has-treeview {{ $prefix =='/employee' ? 'menu-open' : '' }}">

    <a href="#" class="nav-link {{ $prefix =='/employee' ? 'active' : '' }}">
        <i class="nav-icon fas fa-users"></i>
        <p>
            Employee Manage
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>

    <ul class="nav nav-treeview">

        <li class="nav-item ">
            <a href="{{ route('employee.add') }}" class="nav-link {{ $route == 'employee.add' ? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p> New Employee</p>
            </a>
        </li>

        <li class="nav-item ">
            <a href="{{ route('employee.view') }}" class="nav-link {{ $route == 'employee.view' ? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p> ALL Employees</p>
            </a>
        </li>
    </ul>
</li>


<li class="nav-item has-treeview {{ $prefix =='/attendance' ? 'menu-open' : '' }}">

    <a href="#" class="nav-link {{ $prefix =='/attendance' ? 'active' : '' }}">
        <i class="nav-icon fas fa-clipboard"></i>
        <p>
            Attendance Manage
            <i class="fas fa-angle-left right"></i>
        </p>
    </a>

    <ul class="nav nav-treeview">

        <li class="nav-item ">
            <a href="{{ route('attendance.add') }}" class="nav-link {{ $route == 'attendance.add' ? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p> New Attendance</p>
            </a>
        </li>

        <li class="nav-item ">
            <a href="{{ route('attendance.view') }}" class="nav-link {{ $route == 'attendance.view' ? 'active' : '' }}">
                <i class="far fa-circle nav-icon"></i>
                <p> ALL Attendance</p>
            </a>
        </li>
    </ul>
</li>

--}}

resources/views/include/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy; {{ Date('Y') }} <a href="http://ruarman.com" target="_blank">Ripon uddin Arman</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 3.0.1
    </div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{ asset('admin/plugins/jquery/jquery.min.js')}}"></script>

<script src="{{ asset('admin/plugins/select2/js/select2.js')}}"></script>
<script src="{{ asset('admin/js/barcode.js')}}"></script>

<!-- Summernote -->
<script src="{{ asset('admin/plugins/summernote/summernote-bs4.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->

<script>
    $(document).ready(function () {
        $('.select2').select2();
        $('.description').summernote({
            airMode: false
        });
    });
</script>

<script src="{{ asset('admin/js/sweetalert.min.js') }}"></script>
<script src="{{ asset('admin/js/notify.min.js') }}"></script>


<script src="{{ asset('admin/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
<script src="{{ asset('admin/plugins/daterangepicker/daterangepicker.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    /*$.widget.bridge('uibutton', $.ui.button)*/
</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('admin/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- ChartJS -->
<!-- Sparkline -->
<script src="{{ asset('admin/plugins/sparklines/sparkline.js')}}"></script>
<!-- JQVMap -->
<script src="{{ asset('admin/plugins/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{ asset('admin/plugins/jqvmap/maps/jquery.vmap.usa.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('admin/plugins/jquery-knob/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{ asset('admin/plugins/moment/moment.min.js')}}"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="{{ asset('admin/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<!-- overlayScrollbars -->
<script src="{{ asset('admin/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/dist/js/adminlte.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('admin/dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('admin/dist/js/demo.js')}}"></script>


<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.6.1/js/buttons.print.min.js"></script>

resources/views/include/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ route('home') }}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>



        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link online" id="online" style="background: #000;color: #fff;"></a>

        </li>
    </ul>


    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar header_search" type="search" placeholder="Search"
                   aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="button">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Messages Dropdown Menu -->

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
              <p class="bg-info" style="padding: 5px;">   {{ Auth::user()->name }} </p>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i> Member Since
                    <span class="float-right text-muted text-sm"> {{ Auth::user()->created_at->diffForHumans()  }}</span>
                </a>


                <a href="#" class="dropdown-item">
                    <i class="fas fa-user mr-2"></i> Register Date
                    <span class="float-right text-muted text-sm"> {{ \Carbon\Carbon::parse(Auth::user()->created_at)->format('D-d-M-Y ') }}</span>
                </a>

                {{ Form::open(['route'=>'logout','method'=>'form-control']) }}
                <a href="#" class="dropdown-item">

                    <p class="">
                    {{ Form::submit('Log Out',['class'=>'btn-danger btn fas fa-sign-out-alt mr-2']) }}

                    </p>
                </a>
                {{ Form::close() }}

            </div>
        </li>
       {{-- <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#">
                <i class="fas fa-th-large"></i>
            </a>
        </li>--}}
    </ul>
</nav>