routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\App;

Route::get('locale/{locale}', function ($locale){
    Session::put('hr_locale',$locale);
    return redirect("/");
});


Route::get('reboot',function (){
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
});


Route::get('/', function () {
    return view('auth.login');
})->name('/');


Route::get('dynamic-web','backend\WebController@index');
Route::get('assign','backend\WebController@assign');

Auth::routes();


Route::middleware(['CheckPermit','auth'])->group(function (){

    Route::prefix('UserManagement')->group(function (){
        /* Custom Registration Start */
        Route::get('add-user','backend\UserController@index')->name('user.add');
        Route::get('view-user','backend\UserController@index')->name('user.view');
        Route::post('store-user','backend\UserController@store')->name('user.store');
        Route::get('edit-user/{id}','backend\UserController@edit')->name('user.edit');
        Route::post('update-user/{id}','backend\UserController@update')->name('user.update');
        Route::post('destroy-user','backend\UserController@destroy')->name('user.destroy');
        /* Custom Registration Start */
    });

    /* Role & Permission Start */
    Route::prefix('Role-Permission')->group(function (){

        /* Permission Settings  Start
        === We Can Enable it if you wants to add Route information dynamically through Form.
        */
        /*Route::get("add-permission","backend\PermissionController@index")->name('permission.add');
        Route::post("/save-permission","backend\PermissionController@store")->name('permission.store');
        Route::get("/edit-permission/{id}","backend\PermissionController@edit")->name('permission.edit');
        Route::post("/update-permission/{id}","backend\PermissionController@update")->name('permission.update');
        Route::post("/destroy-permission","backend\PermissionController@destroy")->name('permission.destroy');*/
        /* Permission Settings  Start */

        /* Role Create Start  */
        Route::get('add-role','backend\RoleController@index')->name('role.add');
        Route::get('view-role','backend\RoleController@index')->name('role.view');
        Route::post('store-role','backend\RoleController@store')->name('role.store');
        Route::get('edit-role/{id}','backend\RoleController@edit')->name('role.edit');
        Route::post('update-role/{id}','backend\RoleController@update')->name('role.update');
        Route::post('destroy-role','backend\RoleController@destroy')->name('role.destroy');
        /* Role Create End  */
    });
    /* Role & Permission End */

    Route::prefix('admin')->group(function (){
        Route::get('/home', 'HomeController@index')->name('home');
        Route::get('change-password','backend\UserController@changePassword')->name('admin.password-change');
        Route::post('update-admin/{id}','backend\UserController@updateAdmin')->name('admin.update');
    });

    Route::prefix('employee')->name('employee.')->group(function (){
        $employeeController = 'backend\EmployeeController@';
        Route::get('/new-employee',$employeeController.'index')->name('add');
        Route::get('/edit-employee/{id}',$employeeController.'edit')->name('edit');
        Route::get('/view-employee',$employeeController.'view')->name('view');
        Route::post('/store-employee',$employeeController.'store')->name('store');
        Route::post('/update-employee/{id}',$employeeController.'update')->name('update');
        Route::post('/destroy-employee',$employeeController.'destroy')->name('destroy');
        Route::get('/archive-employee',$employeeController.'archive')->name('archive');
        Route::post('/restore-employee/{id}',$employeeController.'restore')->name('restore');
    });

    Route::prefix('attendance')->name('attendance.')->group(function (){
        $attendanceController = 'backend\AttendanceController@';
        Route::get('/new-attendance',$attendanceController.'index')->name('add');
        Route::get('/edit-attendance/{id}',$attendanceController.'edit')->name('edit');
        Route::get('/view-attendance',$attendanceController.'view')->name('view');
        Route::post('/store-attendance',$attendanceController.'store')->name('store');
        Route::post('/single-update-attendance/{id}',$attendanceController.'singleUpdate')->name('single-update');
    });
});

app/Attendance.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Attendance extends Model
{
    protected $table = 'attendances';
    protected $fillable = ['employee_id', 'designation_id', 'date', 'enter_time', 'leave_time'];

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    public function designation()
    {
        return $this->belongsTo(Designation::class);
    }
}

app/Http/Controllers/backend/AttendanceController.php
<?php

namespace App\Http\Controllers\backend;

use App\Attendance;
use App\Employee;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AttendanceController extends Controller
{
    public function index()
    {


        /* if Form Get Request Found*/
        if (isset($_GET['find_designation_id']))
        {
            $designations = decrypt($_GET['find_designation_id']);

            $data['employees'] = Employee::query()->where('designation_id','=',$designations)->get();
        }else{
            $data['employees'] = null;
        }

        $data['designations'] = Employee::query()
            ->groupBy('designation_id')
            ->get();
        return view('attendance.add-attendance')->with($data);
    }

    public function store(Request $request)
    {

        $this->validate($request,[
            'employee_id'=>'required',
            'enter_time'=>'required',
        ]);


        foreach ($request->employee_id as $key=>$employee)
        {
            $e = Employee::query()->findOrFail($employee);

            Attendance::query()->create([
                'employee_id' =>$e->id,
                'date'=>$request->date,
                'designation_id'=>$e->designation_id,
                'enter_time'=>$request->enter_time[$key],
                'leave_time'=> isset($request->leave_time[$key]) ? $request->leave_time[$key] : null,
            ]);
        }
        session()->flash('success','Attendance saved');
        return redirect()->route('attendance.add');
    }


    public function view()
    {

        /* if Form Get Request Found*/
        if (isset($_GET['find_designation_id']))
        {
            $designations = decrypt($_GET['find_designation_id']);
            $date = $_GET['date'];
            $data['attendances'] = Attendance::query()->where('designation_id','=',$designations)
                ->where('date','=',$date)
                ->get();
        }else{
            $data['attendances'] = Attendance::query()->orderByDesc('id')->get();
        }

        $data['designations'] = Attendance::query()->groupBy('designation_id')->get();

        return view('attendance.view-attendance')->with($data);
    }

    public function edit($id)
    {
        $id = decrypt($id);
        $attendance = Attendance::query()->findOrFail($id);
        return view('attendance.edit-attendance',compact('attendance'));
    }

    public function singleUpdate(Request $request,$id)
    {
        $id = decrypt($id);
        $attendance = Attendance::query()->findOrFail($id);
        $attendance->update([
            'enter_time'=>$request->enter_time,
            'leave_time'=>$request->leave_time,
        ]);

        $employee = Employee::query()->findOrFail($attendance->employee_id);

        session()->flash('success',$employee->name. ' - attendance updated');
        return redirect()->route('attendance.add');

    }

}

resources/views/attendance/add-attendance.blade.php
@extends('layouts.admin')

@section('title','New Attendance | HR Application')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Employee Attendance</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Attendance </li>
                    </ol>
                </div><!-- /.col -->

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('attendance.view') }}" class="btn btn-success pull-right"> ALL
                                Attendances</a>
                        </div>
                    </div>

                </div>

            </div><!-- /.row -->


        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">New Attendance</h3>
                        </div>
                        <div class="card-body">
                            {{ Form::open(['route'=>'attendance.add','method'=>'get']) }}
                            <div class="row">
                                @include('attendance.form-attendance')
                            </div>

                            {{ Form::close() }}
                        </div>
                    </div>
                </div>

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Employee List </h3>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table class="table-hover table">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            <th>Name</th>
                                            <th>Designation</th>
                                            <th>Enter Time</th>
                                            <th>Leave Time</th>
                                        </tr>
                                    </thead>

                                    <tbody>


                            {{ Form::open(['route'=>'attendance.store','method'=>'post']) }}

                              @if($employees !=null)
                                @foreach($employees as $key=>$employee)

                                    <td>{{ $loop->iteration }}</td>
                                    <td>
                                        {{ $employee->name }}
                                        {{ Form::hidden('employee_id[]',$employee->id) }}
                                        {{ Form::hidden('date',$_GET['date']) }}
                                    </td>

                                    <td>  {{ $employee->designation->name }}      </td>

                                    <td>
                                        <input
                                               type="time"
                                               class="form-control"
                                               name="enter_time[]"
                                                required
                                        >
                                    </td>
                                    <td>
                                         <input
                                            type="time"
                                            class="form-control"
                                            name="leave_time[]" />
                                    </td>

                                @endforeach

                              @endif


                                    </tbody>

                                    <tfoot>
                                        <tr>
                                            <td class="text-center" colspan="5">
                                                {{ Form::submit('Save Attendance',['class'=>'btn btn-info']) }}
                                            </td>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>

                            {{ Form::close() }}
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("#dataTable").DataTable();
        });
    </script>
@endsection

resources/views/attendance/edit-attendance.blade.php
@extends('layouts.admin')

@section('title','New Attendance | HR Application')

@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Employee Attendance</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">New Attendance </li>
                    </ol>
                </div><!-- /.col -->

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('employee.view') }}" class="btn btn-success pull-right"> ALL Employees</a>
                            <a href="{{ route('employee.archive') }}" class="btn btn-danger pull-right" style="float:
                            right"> Archive Employees</a>
                        </div>
                    </div>

                </div>

            </div><!-- /.row -->


        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"> <i>{{ $attendance->employee->name }}</i> - attendance Update </h3>
                        </div>
                        <div class="card-body">

                            <div class="table-responsive">
                                <table class="table-hover table">
                                    <thead>
                                        <tr>
                                            <th>SL</th>
                                            <th>Name</th>
                                            <th>Designation</th>
                                            <th>Enter Time</th>
                                            <th>Leave Time</th>
                                        </tr>
                                    </thead>
                                <tbody>
                                    {{ Form::open(['route'=>['attendance.single-update',encrypt($attendance->id)],
                                    'method'=>'post']) }}
                                            <td>1</td>
                                            <td>
                                                {{ $attendance->employee->name }}
                                                {{ Form::hidden('employee_id',$attendance->id) }}
                                            </td>

                                            <td>  {{ $attendance->designation->name }} </td>

                                            <td>
                                                <input
                                                    type="time"
                                                    class="form-control"
                                                    name="enter_time"
                                                    required
                                                    value="{{ $attendance->enter_time }}"
                                                >
                                            </td>
                                            <td>
                                                <input
                                                    type="time"
                                                    class="form-control"
                                                    name="leave_time"
                                                    value="{{ $attendance->leave_time }}"
                                                />
                                            </td>

                                    </tbody>

                                    <tfoot>
                                    <tr>
                                        <td class="text-center" colspan="5">
                                            {{ Form::submit('Update Attendance',['class'=>'btn btn-info']) }}
                                        </td>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>

                            {{ Form::close() }}
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("#dataTable").DataTable();
        });
    </script>
@endsection

resources/views/attendance/form-attendance.blade.php
<div class="col-lg-4">
    <div class="form-group @error('designation_id') has-error @enderror ">
        {{ Form::label('','Designation *') }}
        <select name="find_designation_id" class="form-control" id="">
            @foreach($designations as $key=>$designation)
                <option value="{{ encrypt($designation->designation_id) }}">{{ $designation->designation->name }}</option>
            @endforeach
        </select>

        @error('designation_id')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>

<div class="col-lg-4">
    <div class="form-group @error('join_date') has-error @enderror ">
        {{ Form::label('','Attendance Date *') }}
        {{ Form::date('date',isset($_GET['date']) ? $_GET['date'] : null,['class'=>'form-control','required',
        'placeholder'=>'Ex
        .2020-06-21']) }}

        @error('join_date')
        <span class="strong">
                <strong class="help-block"> {{ $message }}</strong>
            </span>
        @enderror
    </div>
</div>


<div class="col-lg-4">
    <div class="form-group " style="padding-top: 32px;">
        {{ Form::submit('Find Employees',['class'=>'btn btn-success']) }}
    </div>
</div>

resources/views/attendance/view-attendance.blade.php
@extends('layouts.admin')
@section('title','ALL Attendance - HR Application')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Attendance Management</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">View Attendance </li>
                    </ol>
                </div><!-- /.col -->

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ route('attendance.add') }}" class="btn btn-success pull-right"> New
                                Attendance</a>

                        </div>
                    </div>
                </div>


            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- Main content -->

    <section class="content">
        <div class="container-fluid">
            {{-- Cart Item Start --}}
            <div class="row">
                <!-- ./col -->

                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Filter Attendance</h3>
                        </div>
                        <div class="card-body">
                            {{ Form::open(['route'=>'attendance.view','method'=>'get']) }}
                            <div class="row">
                                @include('attendance.form-attendance')
                            </div>

                            {{ Form::close() }}
                        </div>
                    </div>
                </div>


                <div class="col-lg-12 col-xs-12">
                    {{-- all users retrive start --}}
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">ALL Attendance</h3>
                        </div>
                        <div class="card-body table-responsive">
                            <table class="table table-hover" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>#SL</th>
                                        <th>Avatar</th>
                                        <th>Name</th>
                                        <th>Designation</th>
                                        <th>Date</th>
                                        <th>Enter</th>
                                        <th>Leave</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                                @if(isset($_GET['find_designation_id']))
                                    @if($attendances->count()>0)
                                        @foreach($attendances as $key=>$employee)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>
                                                    <img src="{{ $employee->avatar !=null ? asset('upload/employee/'
                                                    .$employee->avatar) : asset('upload/noimage.png') }}"
                                                         style="height:
                                                    100px;width: 100px" alt="">
                                                </td>
                                                <td>{{ $employee->employee->name }}</td>

                                                <td>{{ $employee->designation->name }}</td>
                                                <td>{{ $employee->date }}</td>
                                                <td>
                                                    @php
                                                        $timeEx = explode(":",$employee->enter_time);
                                                        $leaveTime = explode(":",$employee->leave_time);
                                                    @endphp
                                                    {{ $employee->enter_time }}
                                                    {{ $employee->enter_time!=null && $timeEx[0]>12 ||
                                                    $timeEx[0]==12 ? 'PM' : 'AM' }}
                                                </td>
                                                <td>{{ $employee->leave_time }} {{ $employee->leave_time!=null &&
                                                $leaveTime[0]>12 ||
                                                $leaveTime[0]==12 ? 'PM' : 'AM' }}</td>
                                                <td>

                                                    <a href="{{ route('attendance.edit',encrypt( $employee->id)) }}" class="fa
                                                    fa-edit bg-success ml-2 p-2
                                                    rounded"></a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                @else
                                    @if($attendances->count()>0)
                                        @foreach($attendances as $key=>$employee)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>
                                                    <img src="{{ $employee->avatar !=null ? asset('upload/employee/'
                                                    .$employee->avatar) : asset('upload/noimage.png') }}"
                                                         style="height:
                                                    100px;width: 100px" alt="">
                                                </td>
                                                <td>{{ $employee->employee->name }}</td>

                                                <td>{{ $employee->designation->name }}</td>
                                                <td>{{ $employee->date }}</td>
                                                <td>
                                                    @php
                                                        $timeEx = explode(":",$employee->enter_time);
                                                        $leaveTime = explode(":",$employee->leave_time);
                                                    @endphp
                                                    {{ $employee->enter_time }}
                                                    {{ $employee->enter_time!=null && $timeEx[0]>12 ||
                                                    $timeEx[0]==12 ? 'PM' : 'AM' }}
                                                </td>
                                                <td>{{ $employee->leave_time }} {{ $employee->leave_time!=null &&
                                                $leaveTime[0]>12 ||
                                                $leaveTime[0]==12 ? 'PM' : 'AM' }}</td>
                                                <td>

                                                    <a href="{{ route('attendance.edit',encrypt( $employee->id)) }}" class="fa
                                                    fa-edit bg-success ml-2 p-2
                                                    rounded"></a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif
                                @endif
                                </tbody>
                            </table>
                        </div>
                        {{-- all users retrive end --}}
                    </div>

                </div>

            </div>


    </section>
    <!-- /.content -->

@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $("#dataTable").DataTable();
        });
    </script>
@endsection